### PR TITLE
feat: Move files to .trash folder if they are in use

### PR DESCRIPTION
**Pull request by adament**
### Description

Attempt to move files to .trash folder if they are in use, this should solve #578. The issue is that on Windows we cannot delete files that are in use. When using a global package cache and hardlinking files into environments this means that if a given DLL or exe is in use in any environment with the same package the deletion files. But we can rename the hardlink. Conda and mamba have similar fallback behaviour.

The solution in this PR is slightly different than the ones used in conda and mamba as far as I am aware. This PR:

* Creates a folder in `.trash` in the root of the environment rather than having a file like mamba_trash.txt to keep track of all the files which could not be deleted. Then a separate empty_trash procedure should simply attempt to delete all files in the .trash folder and if successful, it should remove the `.trash` folder.
* When moving a file to `.trash` it is renamed to `uuid.rattler_trash`. Mamba and conda kept the original filename and appended `.mamba_trash`, but then they had to worry about filename collisions and having some fallback procedure for coming up with new names on a collision. It thus seemed simpler to me to just give a unique name to each file in the trash folder. Though in this way we lose information about the origin of the file.

Please tell me if you think the approach or the implementation is wrong.

### CODE REVIEW

**Comment by wolfv** [comment]
Awesome! I am wondering - did you check that "moving" to a different folder works when the file is in use? If yes, then this is a great solution. 

I also thought that we could try to have `filename.<uuid>.trash` as a filename but it might get longer than the allowed length. 

I think going for UUID is fine with me. We would probably also be on the safe side with, idk, filename + 4 random characters or so.

There are also ways to add metadata to files that are NTFS specific (similar to xattrs on Unix) but not sure if that would be worth it to investigate.

**Comment by baszalmstra** [comment]
Lets add the filename indeed to make it slightly easier to debug. If filename becomes to long we can worry about it then.

**Comment by adament** [comment]
I have changed it to the filename.<uuid>.trash pattern and attempted to make the test more robust.

**Comment by baszalmstra** [comment]
Thank you so much for this PR and your patience reviewing our comments! Highly appreciated! :)

**Comment by adament** [comment]
Thank you for taking the time to review and comment.

**Pull request merged**
